import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from installer.actions import FilePlan
from scripts.release_bundle import RUNTIME_PATHS

if TYPE_CHECKING:
    from collections.abc import Iterator

SCHEMA_VERSION = 1
MIN_PYTHON = (3, 14)


class UnsupportedInterpreterError(RuntimeError): ...


def resolve_interpreter() -> str:
    if sys.version_info[:2] < MIN_PYTHON:
        got = '.'.join(str(part) for part in sys.version_info[:2])
        wanted = '.'.join(str(part) for part in MIN_PYTHON)
        raise UnsupportedInterpreterError(
            f'resolved interpreter {sys.executable} is Python {got}; '
            f'agentmaster requires >= {wanted}'
        )
    return Path(sys.executable).as_posix()


def _is_source_file(path: Path) -> bool:
    return path.is_file() and '__pycache__' not in path.parts and path.suffix != '.pyc'


def _iter_source_files(root: Path) -> Iterator[Path]:
    for entry in RUNTIME_PATHS:
        source = root / entry
        if source.is_dir():
            yield from sorted(path for path in source.rglob('*') if _is_source_file(path))
        elif _is_source_file(source):
            yield source


def runtime_plans(root: Path, agentmaster_home: Path) -> list[FilePlan]:
    runtime_dir = agentmaster_home / 'runtime'
    return [
        FilePlan(
            content=source.read_text(encoding='utf-8'),
            destination=runtime_dir / source.relative_to(root),
        )
        for source in _iter_source_files(root)
    ]


_LAUNCHER_TEMPLATE = '''#!{interpreter}
"""Installed agentmaster launcher -- checkout-independent CLI entrypoint.

Generated by the installer; a reinstall regenerates and overwrites it.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'runtime'))

from agentmaster.cli import main

if __name__ == '__main__':
    raise SystemExit(main())
'''


def launcher_plan(agentmaster_home: Path, interpreter: str) -> FilePlan:
    return FilePlan(
        content=_LAUNCHER_TEMPLATE.format(interpreter=interpreter),
        destination=agentmaster_home / 'bin' / 'agentmaster',
        executable=True,
    )


@dataclass(frozen=True, slots=True)
class RuntimeDescriptor:
    config_path: Path
    launcher: Path
    ledger_path: Path | None
    ledger_enabled: bool
    artifact_dir: Path
    schema_version: int = SCHEMA_VERSION

    def render(self) -> str:
        document = {
            'config_path': str(self.config_path),
            'launcher': str(self.launcher),
            'ledger_path': str(self.ledger_path)
            if self.ledger_path is not None
            else None,
            'ledger_enabled': self.ledger_enabled,
            'artifact_dir': str(self.artifact_dir),
            'schema_version': self.schema_version,
        }
        return json.dumps(document, indent=2) + '\n'


def descriptor_plan(destination: Path, descriptor: RuntimeDescriptor) -> FilePlan:
    return FilePlan(content=descriptor.render(), destination=destination)
