"""Installed narrow runtime: source copy, launcher, and per-target descriptor.

Decouples the installed hooks from the source checkout (evidence 12/13 in
the ledger-runtime plan): `<agentmaster-home>/runtime/` holds a copy of the
runtime sources (`scripts.release_bundle.RUNTIME_PATHS`, the same set the
release archive bundles), `<agentmaster-home>/bin/agentmaster` is a narrow
launcher pinning a >=3.14 interpreter and locating that copy relative to its
own installed location, and a `runtime.json` descriptor beside each target's
installed hooks (the Runtime descriptor contract) tells the standalone hooks
where to find the canonical config/ledger/artifacts without ever importing
`ledger` in-process.
"""

import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from installer.actions import FilePlan
from scripts.release_bundle import RUNTIME_PATHS

if TYPE_CHECKING:
    from collections.abc import Iterator

SCHEMA_VERSION = 1
MIN_PYTHON = (3, 14)


class UnsupportedInterpreterError(RuntimeError):
    """The interpreter resolved at install time is older than `MIN_PYTHON`."""


def resolve_interpreter() -> str:
    """Return the abs path of the interpreter to pin the launcher to.

    Raises
    ------
    UnsupportedInterpreterError
        The running interpreter is older than the project's `>=3.14` floor;
        pinning the launcher to it would silently break the installed hooks,
        which rely on 3.14-only syntax (PEP 758).
    """
    if sys.version_info[:2] < MIN_PYTHON:
        got = '.'.join(str(part) for part in sys.version_info[:2])
        wanted = '.'.join(str(part) for part in MIN_PYTHON)
        raise UnsupportedInterpreterError(
            f'resolved interpreter {sys.executable} is Python {got}; '
            f'agentmaster requires >= {wanted}'
        )
    return Path(sys.executable).as_posix()


def _is_source_file(path: Path) -> bool:
    """True for a real tracked-style source file, never a bytecode cache artifact.

    `git archive` (what the release bundle actually ships) only ever
    includes tracked files, so it can't pick up `__pycache__/*.pyc`; walking
    the live working tree here must reproduce that filter explicitly.
    """
    return path.is_file() and '__pycache__' not in path.parts and path.suffix != '.pyc'


def _iter_source_files(root: Path) -> Iterator[Path]:
    """Yield every file under `root` named by `RUNTIME_PATHS`, deterministically."""
    for entry in RUNTIME_PATHS:
        source = root / entry
        if source.is_dir():
            yield from sorted(path for path in source.rglob('*') if _is_source_file(path))
        elif _is_source_file(source):
            yield source


def runtime_plans(root: Path, agentmaster_home: Path) -> list[FilePlan]:
    """File plans copying the runtime sources under `<agentmaster_home>/runtime/`."""
    runtime_dir = agentmaster_home / 'runtime'
    return [
        FilePlan(
            content=source.read_text(encoding='utf-8'),
            destination=runtime_dir / source.relative_to(root),
        )
        for source in _iter_source_files(root)
    ]


_LAUNCHER_TEMPLATE = '''#!{interpreter}
"""Installed agentmaster launcher -- checkout-independent CLI entrypoint.

Generated by the installer; a reinstall regenerates and overwrites it.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'runtime'))

from agentmaster.cli import main

if __name__ == '__main__':
    raise SystemExit(main())
'''


def launcher_plan(agentmaster_home: Path, interpreter: str) -> FilePlan:
    """The file plan for `<agentmaster_home>/bin/agentmaster`."""
    return FilePlan(
        content=_LAUNCHER_TEMPLATE.format(interpreter=interpreter),
        destination=agentmaster_home / 'bin' / 'agentmaster',
        executable=True,
    )


@dataclass(frozen=True, slots=True)
class RuntimeDescriptor:
    """The Runtime descriptor contract fields, no secrets."""

    config_path: Path
    launcher: Path
    ledger_path: Path | None
    ledger_enabled: bool
    artifact_dir: Path
    schema_version: int = SCHEMA_VERSION

    def render(self) -> str:
        document = {
            'config_path': str(self.config_path),
            'launcher': str(self.launcher),
            'ledger_path': str(self.ledger_path)
            if self.ledger_path is not None
            else None,
            'ledger_enabled': self.ledger_enabled,
            'artifact_dir': str(self.artifact_dir),
            'schema_version': self.schema_version,
        }
        return json.dumps(document, indent=2) + '\n'


def descriptor_plan(destination: Path, descriptor: RuntimeDescriptor) -> FilePlan:
    """The file plan for the `runtime.json` descriptor at `destination`."""
    return FilePlan(content=descriptor.render(), destination=destination)
